version: "3.9"
services:
  back:
    build:
     context: ./src
     target: finalApp
    image: myahiatene/salesTax-back
    container_name: salesTax-backend
    ports:
     - "8080:8080"
    networks:
      - frontback

  front:
    build: ./front
    image: yahiadev/books-front
    container_name: books-front
    ports:
      - 8080:8080
    depends_on:
      - back
    networks: 
      - frontback

networks: 
 frontback:
  driver: bridge
